version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
      - environment_app-environment

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "443:443"
      - "8089:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
      
#Docker Networks
networks:
  app-network:
    driver: bridge
  environment_app-environment:
    external: true
#Volumes
volumes:
  dbdata:
    driver: local
